export const ErrorCode = {
    // 通用错误
    SYSTEM_ERROR: 'SYSTEM_ERROR',
    INVALID_PARAMS: 'INVALID_PARAMS',
    
    // 用户相关错误
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_EXISTS: 'USER_EXISTS',
    USER_STATUS_ERROR: 'USER_STATUS_ERROR',
    
    // 认证相关错误
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    NO_TOKEN_PROVIDED: 'NO_TOKEN_PROVIDED',
    INVALID_AUTH_STRATEGY: 'INVALID_AUTH_STRATEGY',
    
    // 手机号相关错误
    PHONE_EXISTS: 'PHONE_EXISTS',
    INVALID_PHONE: 'INVALID_PHONE',
    INVALID_PHONE_CODE: 'INVALID_PHONE_CODE',
    INVALID_PHONE_VERIFICATION_CODE: 'INVALID_PHONE_VERIFICATION_CODE',
    PHONE_VERIFICATION_CODE_EXPIRED: 'PHONE_VERIFICATION_CODE_EXPIRED',
    
    // 密码相关错误
    PASSWORD_ERROR: 'PASSWORD_ERROR',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    
    // 邮箱相关错误
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_EMAIL_CODE: 'INVALID_EMAIL_CODE',
    INVALID_EMAIL_VERIFICATION_CODE: 'INVALID_EMAIL_VERIFICATION_CODE',
    EMAIL_VERIFICATION_CODE_EXPIRED: 'EMAIL_VERIFICATION_CODE_EXPIRED',
    
    // 微信相关错误
    WECHAT_ERROR: 'WECHAT_ERROR',
    WECHAT_USER_NOT_FOUND: 'WECHAT_USER_NOT_FOUND',
} as const; 